// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/usermgm/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	FirstName            string               `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string               `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	UserName             string               `protobuf:"bytes,5,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Image                string               `protobuf:"bytes,6,opt,name=Image,proto3" json:"Image,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               int64                `protobuf:"varint,8,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Birthday             string               `protobuf:"bytes,9,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Address              string               `protobuf:"bytes,10,opt,name=Address,proto3" json:"Address,omitempty"`
	City                 string               `protobuf:"bytes,11,opt,name=City,proto3" json:"City,omitempty"`
	Country              string               `protobuf:"bytes,12,opt,name=Country,proto3" json:"Country,omitempty"`
	Status               bool                 `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy            string               `protobuf:"bytes,15,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,16,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy            string               `protobuf:"bytes,17,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dded8084a41e518e, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CreateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateUserRequest) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *CreateUserRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *CreateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateUserRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateUserRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CreateUserRequest) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateUserRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateUserRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *CreateUserRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CreateUserRequest) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type CreateUserResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dded8084a41e518e, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
}

func init() {
	proto.RegisterFile("proto/v1/usermgm/user/user.proto", fileDescriptor_dded8084a41e518e)
}

var fileDescriptor_dded8084a41e518e = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x71, 0x9a, 0xa6, 0xc9, 0x04, 0x0a, 0x5d, 0x21, 0x3a, 0x44, 0x48, 0x58, 0x11, 0x87,
	0x9c, 0x6c, 0x51, 0x2e, 0x5c, 0xe3, 0x14, 0x50, 0x24, 0x54, 0x45, 0x2e, 0xbd, 0x70, 0xdb, 0xe0,
	0xc1, 0xb5, 0xd4, 0xf5, 0x9a, 0xdd, 0x75, 0x91, 0x3f, 0x09, 0x5f, 0x17, 0xed, 0x1f, 0x3b, 0x95,
	0x8a, 0xc4, 0x25, 0xd9, 0xdf, 0x7b, 0x33, 0x6f, 0x24, 0xcf, 0x40, 0xdc, 0x28, 0x69, 0x64, 0x7a,
	0xff, 0x3e, 0x6d, 0x35, 0x29, 0x51, 0x0a, 0xf7, 0xef, 0x7e, 0x12, 0x67, 0xb1, 0xb1, 0x7d, 0x2f,
	0xde, 0x96, 0x52, 0x96, 0x77, 0x94, 0x3a, 0x6d, 0xdf, 0xfe, 0x4c, 0x4d, 0x25, 0x48, 0x1b, 0x2e,
	0x1a, 0x5f, 0xb6, 0xfc, 0x33, 0x86, 0xb3, 0x8d, 0x22, 0x6e, 0xe8, 0x46, 0x93, 0xca, 0xe9, 0x57,
	0x4b, 0xda, 0xb0, 0x37, 0x30, 0xfb, 0x5c, 0x29, 0x6d, 0xae, 0xb8, 0x20, 0x8c, 0xe2, 0x68, 0x35,
	0xcb, 0x0f, 0x02, 0x5b, 0xc0, 0xf4, 0x2b, 0x0f, 0xe6, 0xc8, 0x99, 0x03, 0xb3, 0x97, 0x70, 0xfc,
	0x49, 0xf0, 0xea, 0x0e, 0x8f, 0x9c, 0xe1, 0xc1, 0x76, 0xec, 0xb8, 0xd6, 0xbf, 0xa5, 0x2a, 0x70,
	0xec, 0x3b, 0x7a, 0xb6, 0x9e, 0x1d, 0xed, 0xd2, 0x8e, 0xbd, 0xd7, 0xb3, 0x4d, 0xdb, 0x0a, 0x5e,
	0x12, 0x4e, 0x7c, 0x9a, 0x03, 0x16, 0xc3, 0x7c, 0x77, 0x2b, 0x6b, 0xba, 0x6a, 0xc5, 0x9e, 0x14,
	0x9e, 0x38, 0xef, 0xa1, 0xc4, 0x5e, 0xc1, 0xe4, 0x0b, 0xd5, 0x05, 0x29, 0x9c, 0xc6, 0xd1, 0xea,
	0x28, 0x0f, 0x64, 0x67, 0x65, 0x95, 0x32, 0xb7, 0x05, 0xef, 0x70, 0xe6, 0x67, 0xf5, 0xcc, 0x10,
	0x4e, 0xd6, 0x45, 0xa1, 0x48, 0x6b, 0x04, 0x67, 0xf5, 0xc8, 0x18, 0x8c, 0x37, 0x95, 0xe9, 0x70,
	0xee, 0x64, 0xf7, 0xb6, 0xd5, 0x1b, 0xd9, 0xd6, 0x46, 0x75, 0xf8, 0xd4, 0x57, 0x07, 0xb4, 0xb3,
	0xaf, 0x0d, 0x37, 0xad, 0xc6, 0x67, 0x71, 0xb4, 0x9a, 0xe6, 0x81, 0xd8, 0x47, 0x98, 0xf9, 0x0f,
	0x5d, 0xac, 0x0d, 0x9e, 0xc6, 0xd1, 0x6a, 0x7e, 0xb1, 0x48, 0xfc, 0x7a, 0x92, 0x7e, 0x3d, 0xc9,
	0xb7, 0x7e, 0x3d, 0xf9, 0xa1, 0xd8, 0x6e, 0x23, 0x40, 0xd6, 0xe1, 0x73, 0xbf, 0x8d, 0x41, 0xb0,
	0xb9, 0x37, 0x4d, 0x11, 0x72, 0x5f, 0xfc, 0x3f, 0x77, 0x28, 0xb6, 0xb9, 0x01, 0xb2, 0x0e, 0xcf,
	0x7c, 0xee, 0x20, 0x2c, 0xdf, 0x01, 0x7b, 0x78, 0x18, 0xba, 0x91, 0xb5, 0x26, 0x76, 0x0a, 0xa3,
	0xed, 0x65, 0x38, 0x89, 0xd1, 0xf6, 0xf2, 0x62, 0x07, 0x73, 0xeb, 0x5f, 0x93, 0xba, 0xaf, 0x7e,
	0x10, 0x5b, 0x03, 0x1c, 0x9a, 0xd8, 0x79, 0xe2, 0x0e, 0xf2, 0xd1, 0x7d, 0x2d, 0xf0, 0xb1, 0xe1,
	0xf3, 0x97, 0x4f, 0xb2, 0xd7, 0xdf, 0xcf, 0x93, 0xf4, 0x9f, 0xe7, 0xbd, 0x9f, 0x38, 0xf9, 0xc3,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x48, 0x4a, 0xd5, 0xfe, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/usermgm/user/user.proto",
}
